### ISSUE TITLE
InverseOf axioms are stated in a verbose fashion

### ISSUE THREAD

**Issue by cmungall** [information-artifact-ontology/IAO#196]
E.g.

```
ObjectProperty: <http://purl.obolibrary.org/obo/IAO_0000221>
...
    EquivalentTo: 
         inverse (<http://purl.obolibrary.org/obo/IAO_0000417>)
```

this is perfectly valid, and any sensible OWL processor can rewrite this in the simpler form using an InverseProperties axiom.

However, not all consumers are capable of this transform, or implement it. And human users of the ontology may get confused. They may look in the 'inverse' slot in Protege and see nothing and miss the equivalence axiom. It may be simpler to reduce each axiom to its simplest form prior to release.

**Comment by cmungall** [comment]
oh and this one is classic:

```
ObjectProperty: <http://purl.obolibrary.org/obo/IAO_0000223>

    
    InverseOf: 
         inverse (<http://purl.obolibrary.org/obo/IAO_0000223>)
```

a tautology and therefore valid... but why... I assume a result of some kind of automated processing

**Comment by alanruttenberg** [comment]
I use the OWLAPI mechanism for adding inferred axioms. It's probably worth putting in an issue with them about this. As it happens doing that caused https://github.com/information-artifact-ontology/IAO/issues/195 and in order to address that in the short term this inference types: [InferredObjectPropertyCharacteristicAxiomGenerator](http://owlcs.github.io/owlapi/apidocs_4/org/semanticweb/owlapi/util/InferredObjectPropertyCharacteristicAxiomGenerator.html) and [InferredSubObjectPropertyAxiomGenerator](http://owlcs.github.io/owlapi/apidocs_4/org/semanticweb/owlapi/util/InferredSubObjectPropertyAxiomGenerator.html)

I will take into consideration the possibility of trying to reduce axioms to simpler forms, but this seems like it might better be taken up by the OWLAPI.

**Comment by alanruttenberg** [comment]
(There is a forthcoming release that fixes the inference issue)

**Comment by alanruttenberg** [comment]
I submitted a ticket to the OWLAPI project that includes this as an issue.
https://github.com/owlcs/owlapi/issues/646
