### ISSUE TITLE
What is realizable, a directive information entity or its concretizations?

### ISSUE THREAD

**Issue by CDowland** [information-artifact-ontology/IAO#231]
I have a question concerning ‘directive information entity’ and its subclasses, especially ‘plan specification.’ Which of the following is the case:

(a) a directive information entity is a realizable entity, or 
(b) a directive information entity has concretizations that are realizable entities?

Concerning this matter, the definitions for ‘directive information entity’ and ‘plan specification’ appear to be inconsistent.  

The definition for ‘directive information entity’ is this: “An information content entity **whose concretizations indicate to their bearer how to realize them** in a process.” That suggests that the concretizations, and not the directive information entity itself, are realizable, and thus is consistent with (b).  

However, ‘plan specification’ (a subclass of ‘directive information entity’) is defined as follows: “A directive information entity with action specifications and objective specifications as parts **that, when concretized, is realized** in a process in which the bearer tries to achieve the objectives by taking the actions specified.” That suggests that it is the plan specification itself, rather than its concretizations, that is a realizable entity, and thus is consistent with (a).  

It should be noted that the definition for OBI’s ‘planned process’—“A processual entity that **realizes a plan which is the concretization of a plan specification**”—is consistent (b) and the definition of ‘directive information entity,’ while inconsistent with that of ‘plan specification.’

**Comment by ECMerr** [comment]
Concretizations themselves are BFO:qualities. Qualities are not realizable entities, so they have no realizations. A directive ICE can give something like instructions on how to proceed (for example with a plan). Actually carrying out the directive ICE will (more than likely) require the realization of various dispositions and roles. The dispositions and roles that are realized in order to carry out the instructions given by the directive ICE obviously have realizations, but this doesn't mean that the 'plan specification' is being realized (according to the formal definitions in BFO, GDCs can't have realizations). However, the information content entity itself is not a realizable entity and cannot have any realizations. 
I find it more than a little confusing sometimes because colloquially we can talk of realizing plans.

**Comment by hoganwr** [comment]
I agree.  However, the definitions very clear state "concretizations indicate to their bearer how to realize them" and "directive information entity...is realized".  There's no other referent for the word 'them' other than 'concretizations' in the definition of 'directive information entity', because it's the only plural that precedes 'them'.  So the definition unequivocally implies that concretizations are realized.  Similarly, the definition of 'plan specification' has subject-verb pair "directive information entity ... is realized" just from the grammatical structure alone.

So the very issues you raise are in the existing definitions, not something Clint suggested.

I will take issue with concretizations being limited to qualities, because BFO mandates no such thing.  The domain of 'concretizes' and range of 'is concretized by' is specifically dependent continuant, not quality.  So roles, dispositions, and functions might also concretize ICEs.  Now BFO doesn't say it sanctions this, but for sure it doesn't rule it out, either, and it's just an error to equate concretizations with qualities in that context.

**Comment by zhengj2007** [comment]
@CDowland The concretization of a directive information entity is realizable. 
‘plan specification’ (a subclass of ‘directive information entity’) is defined as follows: “A directive information entity with action specifications and objective specifications as parts that, when concretized, is realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.” According to the definition, I think it means that a 'plan specification' is realized when it is concretized. So, I don't think there is conflict.

**Comment by ECMerr** [comment]
Okay, I think I see the issue better now. However, the definition of 'realizes' (the object property) is this "Paraphrase of elucidation: a relation between a process and a realizable entity, where there is some material entity that is bearer of the realizable entity and participates in the process, and the realizable entity comes to be realized in the course of the process". The domain for 'realizes' is a process, and the range for 'realizes' is a realizable entity.
Directive ICEs are not realizable entities and neither are concretizations. Is there a different sense of the word "realizes" or "realized in", which is being used in the definition for a directive ICE? If there is, a different word should probably be chosen, since it's contradicting the definitions of the 'realizes' and 'realized in' relations.

**Comment by zhengj2007** [comment]
@hoganwr @CDowland 
Regarding concretization relation, it is used to relate 'generically dependent continuant' to 'specifically dependent continuant'
http://purl.obolibrary.org/obo/RO_0000059 concretizes
http://purl.obolibrary.org/obo/RO_0000058  is concretized as

Actually there are two kinds of concretization. One kind is that an 'information content entity' (ICE) is concretized as a quality and then can be borne by a material entity. The other kind that an ICE (only applied to ‘directive information entity’) is concretized as a realizable entity and then can be realized by a process. 

Here are some related discussions: https://github.com/OBOFoundry/COB/issues/108

**Comment by CDowland** [comment]
@zhengj2007 Yes, as you and I both noted, that definition suggests the plan specification is realizable. But as I also noted, the definitions for 'directive information entity' and 'planned process' both suggest that it is the concretization, rather than the thing being concretized, that is a realizable entity. The conflict is between the definition of 'plan specification' and the other two definitions I mentioned.

Another issue with the definition of 'plan specification' as something that can be realized is that, as both @ECMerr and @hoganwr pointed out, ICEs (or GDCs in general) are not realizable entities.

I think the second issue points to that the problem being with 'plan specification.' If it's definition were altered such that it is the plan/concretization that is realizable, rather than the plan specification itself, then (i) it would no longer treat an ICE as realizable, and (ii) it would be consistent with the other definitions.

**Comment by zhengj2007** [comment]
@CDowland Do you have any suggestion on improving 'plan specification' definition that avoid the confusion? Thanks!

**Comment by CDowland** [comment]
@ECMerr But if the range of 'is concretized as' is 'specifically dependent continuant,' then it is not restricted to just qualities, and leaves open the possibility of something being concretized by realizable entities.

However, I do think it is rather strange to think that if I memorize a song, I have concretized it in my brain with qualities, but that if I memorize a plan (such as a recipe), then I have concretized it in my brain with realizable entities. In either case, I am memorizing a sequence of words. Additionally, an editor note on 'directive information entity' suggests the realizable concretization is created when an intention to follow the direction is formed. So, if I memorize the recipe with no intent to use it, I guess the idea is that it is then just concretized via qualities. If I later form an intention to use the recipe, then it is concretized by something realizable. Does that mean I then have two concretizations of it, one that is qualitative and another that is realizable? Or does it mean that the realizable concretization in some way replaces the qualitative one?

**Comment by CDowland** [comment]
@zhengj2007 Simply rewording it so it is the concretization that is realizable should make it consistent with the other definitions. Something like this: “A directive information entity with action specifications and objective specifications as parts, and whose concretizations can be realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.” But given the concern raised in the preceding comment, I think there may be other problems with 'directive information entity' (and thus with its subclasses).

**Comment by ECMerr** [comment]
@CDowland Yes, I believe that is true. But realizable entities have to be born by material objects. What this may mean is that a material information bearer can also bear a function, which it has based on a particular concretization of an ICE. However, I don't see how a realizable entity itself could concretize an ICE. Even if you memorize a recipe, it seems like the concretization is done using mental representations (which as far as I know are qualities, not realizable entities). Am I off track, or were you thinking something else in regard to your recipe example?

**Comment by CDowland** [comment]
@ECMerr I also have trouble seeing how a realizable entity could concretize an ICE. 

An alternative approach I've thought about is to treat the bearer of the concretization (for example, the portion of my brain in which a recipe is concretized) as the (or part of the) material basis for the corresponding realizable entity. I'm not sure whether the realizable entity would simply be the intention itself, or perhaps something else. This is analogous to the way OGMS depicts a disease as a disposition that has a disorder as its material basis. I'm not sure whether this is an improvement overall, but it at least avoids some of the concerns we've raised here. Your phrasing suggests you might have something similar in mind, as you describe the function as being based on the concretization.

**Comment by hoganwr** [comment]
Getting down some more thoughts about this issue.  Suppose I have memorized my favorite chocolate chip cookie recipe.  It sits there, as an ICE, concretized by various mental representations (the nature of which neuroscience doesn't fully understand and is still elucidating).  However, it's not associated with or about any realizable entities.  It might go years with no one ever intending to follow its instructions.  Now suppose, after a years-long "dormancy", where neither I nor anyone else ever had any intention of following this particular recipe, I wake up one day and say "oh today would be a great day to bake those chocolate chip cookies".  Later I check my kitchen for the ingredients, find that I'm need of some of them, go to the store and buy them, come home, and follow the recipe and bake the cookies.  It is years again before either I or anyone else follows the recipe again.

At some point, some realizable entity came into being.  We can call it a disposition for now, because that's about the only place it fits in the BFO hierarchy.  At some point, I formed the intention to bake those cookies, and became "highly disposed" in favor of carrying out the recipe.  

Relevant questions:
1. What kind of ICE is the recipe?
2. Does it change/add/subtract instantiation of various ICE subtypes during the scenario?  
3. It seems clear that I gain a disposition to bake them once I decide to bake them.  
3a. What is the relationship of this disposition to the recipe?  
3b. What is its relationship or are its relationships to my mental representations of the recipe?
3c. As Clint says, what is the material basis for this disposition?  If the disposition comes and goes, and the mental representations and their bearers do not change, how can the disposition come and go, based on BFO definition?
4. Is there a subtype of disposition something like "intention"?

**Comment by CDowland** [comment]
I know it has been some time, but I want to revisit this. 

I recently considered this issue again and looked back over both the discussion and the relevant terms. 

Two primary concerns were raised before:

**1.** There is an inconsistency among the most relevant terms. I mean such terms as IAO: directive information entity, IAO: plan specification, IAO: objective specification OBI: plan, and OBI: planned process. 

It is IAO: plan specification that is the source of the trouble. The rest are consistent with one another with respect to what is realizable (the concretizations of directive information entities). Of the terms mentioned here, it is only IAO: plan specification that suggests it is the plan specification itself that is realizable (rather than its concretization, i.e., a plan).

Currently, the definition of IAO: plan specification is this:

> A directive information entity with action specifications and objective specifications as parts that, when concretized, is realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.

You can keep the rest of the meaning the same while avoiding the error with something like this:

> A directive information entity with action specifications and objective specifications as parts, and whose concretizations are realizable entities that, if realized, are realized in processes in which the bearer tries to achieve the objectives by taking the actions specified.

That will take care of the root of the first problem, but some effects of it may remain. What I mean is that there are subclasses of IAO: plan specification in which it is instances of that subclass that are said to be realizable, rather than their concretizations. I suspect this is because developers of those terms were basing their definitions on the flawed definition of ‘plan specification.’ For example, IAO: study design and IAO: Postal delivery route both make the same error in their definitions.


**2.** The other problem—or question, at least—arises from OBI: plan, rather than from any IAO terms. Each instance of OBI: plan is, by definition, something its bearer is “committed to realizing.” Thus, we get the scenario where I memorize a cake recipe without intent to make a cake, then have the intent (and thus a plan) for some time, and then (perhaps after making the cake) no longer have the intent/commitment. While I have the plan, does the other, non-realizable concretization still exist, such that I have two concretizations? How is one concretization realizable and the other is not? Surely it is not one concretization that becomes realizable for a time and then ceases to be.

For what it’s worth, my own inclination is to suggest (to OBI) the removal of the requirement of commitment, and treat the commitment/desire/intent to realize the plan as a separate, also realizable entity. One can have the desire to make the cake without a plan for doing so. Likewise, OBI could define things such that one can have the plan without the intent. Then, it is when one has both the plan and the commitment/intent that one will perform or initiate a process that realizes the plan, and in doing so (if successful, at least) also realizes the intent/commitment/desire. (It seems that plans—and other realizable concretizations of directive information entities—are realizable in the sense that they are followable. But a directive—its concretization, that is—remains followable even when there’s no intent to follow it. Of course, there's a need to distinguish a concretization in some who _can_ realize it versus a concretization in, say, a book. But perhaps building commitment into the plan is not the right/only way to do that.)

While this second issue arises from an OBI term, I am wondering what IAO folks think about this matter. Is a concretization of some plan specification only realizable when it inheres in someone who is committed to realizing it, or is it realizable even when that commitment is lacking (perhaps temporarily)?

**Comment by alanruttenberg** [comment]
A note, based on BFO-2020 and my earlier work on these terms. In BFO-2020
concretizations (the unnamed class that is the range of 'concretized as')
may either be specific dependents, currently understood to be either
qualities or realizable entities, or processes. Without considering the
process case, since that is a longer discussion, the intention of the
definition is that directive information entities are the sorts of things
that can either be conconcretized as qualities (e.g. as printed) or as
realizable entities, understood loosely to include plans such as the sort
of things borne  by a brain - things that direct in some sense. This is
different from other information entities which are generally concretized
as qualities.

The prototypical concretizations are the quality carriers of a printed
recipe, or the knowledge of how to do something (loosely speaking).
Directive information connotes something that exists now but which carries
the potential of something happening in the future, a signature of reliable
entities and something that differs from qualities, which manifest as a
whole at any moment in time.

Your proposed revision doesn't work because it reduces the concretizations
to *only* realizable entities. There was some thought in creating the
wording, which at the time seemed to do what it needed to do - add as a
possibility the distinguishing feature the concretization in a realizable
entity.  As I read it now the implication is too strong that the only
concretizations are realizable entities. If there was a change I would make
it would be

A directive information entity with action specifications and objective
specifications as parts *that may be concretized as a realizable entity,*
realized in a process in which the bearer tries to achieve the objectives
by taking the actions specified.

The one active debate in this area is over what a "plan" is, which is why
that term is not defined and used in an informal sense in the definitions.
The dispute is over whether plans include only cases where there is an
intention to actually realize - "taken up" plans. My feeling is that the
word "plan" is ambiguous and that there are two classes - one with
intention to complete, and one with only potential but not intention.

Alan

**Comment by CDowland** [comment]
Thanks for catching my error with respect to implying all concretizations are realizable (it wasn't what I had in mind, but is certainly what I wrote).

Your proposed change may be too strong in a different way. While it does not suggest each concretization is realizable, it seems to suggest each realizable concretization is realized. But a plan can inhere in a person and never be realized. Even if the person is committed to it, various things—such as changing one’s mind or dying before acting on that commitment—might prevent it from being realized. (And while your meaning is clear to me, there might be some ambiguity regarding whether “that may be concretized…” modifies “directive information entity” or “action specifications and objective specifications.")

How about this slight modification instead:

> A directive information entity with action specifications and objective specifications as parts, and that may be concretized as a realizable entity that, if realized, is realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.

This phrasing allows for the possibilities of both (a) non-realizable concretizations and (b) unrealized, realizable concretizations.

**Comment by alanruttenberg** [comment]
> .. it seems to suggest each realizable concretization is realized. 

How so?  The relevant wording is: "a realizable entity that, **if realized**, is realized in a process..."

>But a plan can inhere in a person and never be realized. 

Absolutely. All realizable entities are such that they may or may not be realized.

>there might be some ambiguity regarding whether “that may be concretized…” modifies “directive information entity” or “action specifications and objective specifications.") How about this slight modification instead:

>A directive information entity with action specifications and objective specifications as parts, and that may be concretized as a realizable entity that, if realized, is realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.

This appears to be the same wording as I offered. Did you forget to include your proposed edit?

I take your point about the possibility of confusing whether the concretization is of the DIE or the action/objective specification, though the language seems to me to be unambiguous. The form of the sentence is: "An X with Y and Z as parts, and that may ...". The "and" doesn't seem to have the possibility to attach to other than the DIE. For the referent of "that' to be the parts, it seems to me that ", and" would have to be omitted. But I understand that language can be read differently by different people and I do care that the definition not seem ambiguous. Please suggest a way to make it clearer.

**Comment by CDowland** [comment]
You are confusing my most recent proposed edit with your own. You are quoting portions of mine in order to respond to my objection to yours. Yours did not contain the phrase "if realized," for example. 

Here is your most recent proposed edit in this thread:

> A directive information entity with action specifications and objective specifications as parts *that may be concretized as a realizable entity,* realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.

And here is mine:

> A directive information entity with action specifications and objective specifications as parts, and that may be concretized as a realizable entity that, if realized, is realized in a process in which the bearer tries to achieve the objectives by taking the actions specified.

**Comment by alanruttenberg** [comment]
Hah, so I did. Your definition is clearer, so I'm all for it.

**Comment by CDowland** [comment]
Great, thanks!

**Comment by alanruttenberg** [comment]
@Jie, is this change something you are comfortable making, or does it need further discussion? @CDowland, I haven't edited IAO for a while and @jie is the keeper, so changes should go through her.

**Comment by zhengj2007** [comment]
@alanruttenberg It sounds good to me. Please go ahead to make the changes if you want.

**Comment by alanruttenberg** [comment]
Changes in commit https://github.com/information-artifact-ontology/IAO/commit/f2aba1ddcb56aaed8af2508974d82fc2caf5e45b

Please review after which we can close this.

**Comment by zhengj2007** [comment]
Looks good to me @alanruttenberg
