### ISSUE TITLE
subsume CRID (IAO_0000578 ) under identifier (IAO_0020000)

### ISSUE THREAD

**Issue by StroemPhi** [information-artifact-ontology/IAO#236]
In the context of the [academic event ontology](https://github.com/tibonto/aeon/), most of the needed IDs (e.g. [Wikidata ID](https://www.wikidata.org/wiki/Q43649390), [ROR ID](https://www.wikidata.org/wiki/Q63565260), [ORCID](https://www.wikidata.org/wiki/Q51044), …) are CRIDs ([IAO_0000578](http://purl.obolibrary.org/obo/IAO_0000578)) but we need to use also identifiers that are not centrally registered, such as often just a number on a website (e.g. a WikiCfP-ID) or a distributed identifier (DID) of an event, person or organization on a blockchain. 
 
In an editor note of IAO_0000578 (IAO call 2010-11-24), it is stated:
> We acknowledge that CRID is a subset of a larger identifier class, but this subset fulfills our current needs 

The acknowledged superclass "identifier" [IAO_0020000](http://purl.obolibrary.org/obo/IAO_0020000) has since been created by [Mathias Brochhausen](https://github.com/mbrochhausen) in the PNO and been defined as: 
> An identifier is an information content entity that is the outcome of a dubbing process and is used to refer to one instance of entity shared by a group of people to refer to that individual entity.

Therefore, I propose to subsume CRID under indentifier.
 
This proposal has been seconded by Mathias Brochhausen via email to me on the 2020-11-23.

**Comment by zhengj2007** [comment]
It makes sense to move CRID as a subclass of identifier.

**Comment by alanruttenberg** [comment]
Written name would be a subclass too, then. Probably other terms - I
haven't done a careful review.

That written name is under textual entity now is a symptom of an as-yet
unaddressed problem with IAO namely a way to represent structure or use as
distinct from aboutness. That something is textual speaks to a possible
encoding. That something identifies speaks to aboutness in a more specific
sense: it denotes. In fact, the definition for identifier should include an
axiom to the effect that it denotes something.

I've had a variety of thoughts about this over the years. The one that is
spiritually closest to BFO would be to define information entity roles,
currently blocked because BFO doesn't allow dependents on dependents. We
could define an information role l in a parallel manner to role, but I'm
not sure where that would be put wrt to BFO. Maybe GDC.  This would address
use more than structure, but I think use is the lower hanging fruit, and
would solve the current problem.

Or, we could review terms that are focused on encoding, such as textual
entity, and instead use a relation that captures the encoding. For a
textual entity a candidate definition might be  an: information content
entity that has at least one concretization that at some time that is
rendered as visual text. Not sure that captures the sense quite right. We'd
need to review those terms and discuss the definition. A little work would
have to be done to explain what is rendering as text means, but I think
that's doable.

Using either approach would allow textual entity and its subclasses to be
defined classes and so would let us have a single asserted hierarchy
instead of having multiple asserted parents for a term  which presumably
must otherwise be done to accommodate name as identifier. The information
role approach would be more consequential - I'd be curious what Barry
thinks of it - but it's the one that would allow better representation of a
bunch of existing terms. In the case of textual entity, tt would allow us
to, instead of saying it *has* a concretization as text, say that it's
information-role is information-realized as concretizing an ICE as text.
That works better for examples of machine created text that are *intended*
to be rendered as text, but never actually are.

I have some other ideas, but they would need a more radical reorganization
of IAO.

Alan

**Comment by zhengj2007** [comment]
The issue solved in release 2020-12-09. I close this tracker and please use tracker #237 for more issues related to PNO.

Hi @alanruttenberg, could you please post your comments on the tracker:
https://github.com/information-artifact-ontology/IAO/issues/237

Thanks!
