### ISSUE TITLE
Obligee, Obligor, and Owner Roles - Where are they?

### ISSUE THREAD

**Issue by lizumberfield** [information-artifact-ontology/IAO#243]
@mbrochhausen - last year we discussed ['obligee role'](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020026), ['obligor role'](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020025), and ['owner role'](https://www.ebi.ac.uk/ols/ontologies/omrse/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0020027) for extending ICO for clinical consent documents. When searching in Ontology Lookup Service, these terms are still discoverable under an IAO purl (see below image). However, they do not appear to be classes in IAO anymore - further they are not discoverable as obsoleted classes. Can you or someone from IAO help me find documentation about where these terms went?

Example
     ![image](https://user-images.githubusercontent.com/44447480/112688029-aca4b200-8e4e-11eb-89cb-770f63516d17.png)

**Comment by mbrochhausen** [comment]
Hi Liz,

regarding d-acts, ontology lookup service is not a locus of authority
(sadly). Even more sadly, Ontobee (currently) cannot not be used for this
purpose, due to an PURL issue created by the OBO Foundry at the time. I am
working with James Overton to resolve that matter, but it might be a few
weeks until that is done.

To look up the newest version of d-acts, please refer to
http://purl.obolibrary.org/obo/iao/d-acts.owl

Best,
Mathias

**Comment by lizumberfield** [comment]
Hi Mathias, 
Thanks for the speedy reply. I appreciate you sending me the most recent version. 
I've also noticed quite a few errors that populate when searching in Ontobee lately, not just with IAO classes. Hoping this gets sorted soon.

Best,
Liz
